Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data.db'
    table: enchantnametag
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: root
    table: enchantnametag

initial-substitution: "\uf100"